### importing important packages that we needed

In [1]:
import requests
from bs4 import BeautifulSoup

#### fetching url by request

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population'
response = requests.get(url)
print(response)

<Response [200]>

#### converting the fetched response into html_text

In [3]:
html_text = response.text

#### creating soup of data to access the data by html tags and classes

In [4]:
soup = BeautifulSoup(html_text , 'lxml')

#### Now with help of soup we can access the html tags by using find or find_all method

In [5]:
data = soup.find_all('table')[1]

In [6]:
# here we got our table we can check it by printing data this will contains all html data of the 
# table we want

In [7]:
raw_headers = data.find_all('th')[1:]    # here we accsing the headers of table

In [8]:
cleaned_headers = []
for header in raw_headers:
    cleaned_headers.append(header.text.strip())
    
print(cleaned_headers)

['Rank', 'State or Union Territory', 'Population[18][19]', '%India', 'Growth', 'Rural pop.', '%rural', 'Urban pop.', '%urban', 'Density[a]', 'Sex ratio', 'Lok Sabha seats', 'Rajya Sabha seats']

### now its time to get information of table

In [9]:
raw_info = data.find_all('tr')[2:]    # index 2 because the data starts from the 3 tr in table

In [10]:
clean_info = []
for row in raw_info:
    row_data = row.find_all('td')
    individual_info = [data.text.strip() for data in row_data]
    individual_info[0] = (individual_info[0].split('('))[0]          # this line is to remove '1(s1)'
    clean_info.append(individual_info)                               #    s1 from rank of all states

In [11]:
print(clean_info)

[['1 ', 'Uttar Pradesh', '199,812,341', '16.51%', '20.2%', '155,317,278', '77.73%', '44,495,063', '22.27%', '828', '912', '80', '31'], ['2 ', 'Maharashtra', '112,374,333', '9.28%', '16%', '61,556,074', '54.78%', '50,818,259', '45.22%', '365', '929', '48', '19'], ['3 ', 'Bihar', '104,099,452', '8.6%', '25.4%', '92,341,436', '88.71%', '11,758,016', '11.29%', '1102', '918', '40', '16'], ['4 ', 'West Bengal', '91,276,115', '7.54%', '13.8%', '62,183,113', '68.13%', '29,093,002', '31.87%', '1029', '953', '42', '16'], ['5 ', 'Madhya Pradesh', '72,626,809', '6%', '20.3%', '52,557,404', '72.37%', '20,069,405', '27.63%', '236', '931', '29', '11'], ['6 ', 'Tamil Nadu', '72,147,030', '5.96%', '15.6%', '37,229,590', '51.6%', '34,917,440', '48.4%', '555', '996', '39', '18'], ['7 ', 'Rajasthan', '68,548,437', '5.66%', '21.3%', '51,500,352', '75.13%', '17,048,085', '24.87%', '201', '928', '25', '10'], ['8 ', 'Karnataka', '61,095,297', '5.05%', '15.6%', '37,469,335', '61.33%', '23,625,962', '38.67%', '319', '973', '28', '12'], ['9 ', 'Gujarat', '60,439,692', '4.99%', '19.3%', '34,694,609', '57.4%', '25,745,083', '42.6%', '308', '919', '26', '11'], ['10 ', 'Andhra Pradesh', '49,577,103[b]', '4.1%', '11.0%', '34,966,693', '70.53%', '14,610,410', '29.47%', '303', '993', '25', '11'], ['11 ', 'Odisha', '41,974,219', '3.47%', '14.0%', '34,970,562', '83.31%', '7,003,656', '16.69%', '269', '979', '21', '10'], ['12 ', 'Telangana', '35,003,674', '2.89%', '13.58%', '21,395,009', '61.12%', '13,608,665', '38.88%', '312', '988', '17', '7'], ['13 ', 'Kerala', '33,406,061', '2.76%', '4.9%', '17,471,135', '52.3%', '15,934,926', '47.7%', '859', '1,084', '20', '9'], ['14 ', 'Jharkhand', '32,988,134', '2.73%', '22.4%', '25,055,073', '75.95%', '7,933,061', '24.05%', '414', '948', '14', '6'], ['15 ', 'Assam', '31,205,576', '2.58%', '17.1%', '26,807,034', '85.9%', '4,398,542', '14.1%', '398', '958', '14', '7'], ['16 ', 'Punjab', '27,743,338', '2.29%', '13.89%', '17,344,192', '62.52%', '10,399,146', '37.48%', '551', '895', '13', '7'], ['17 ', 'Chhattisgarh', '25,545,198', '2.11%', '22.6%', '19,607,961', '76.76%', '5,937,237', '23.24%', '189', '991', '11', '5'], ['18 ', 'Haryana', '25,351,462', '2.09%', '19.9%', '16,509,359', '65.12%', '8,842,103', '34.88%', '573', '879', '10', '5'], ['19 ', 'NCT of Delhi', '16,787,941', '1.39%', '21.2%', '419,042', '2.5%', '16,368,899', '97.5%', '11,297', '868', '7', '3'], ['20 ', 'Jammu and Kashmir', '12,267,032', '1.01%', '23.6%', '9,064,220', '73.89%', '3,202,812', '26.11%', '297', '890', '5', '4'], ['21 ', 'Uttarakhand', '10,086,292', '0.83%', '18.8%', '7,036,954', '69.77%', '3,049,338', '30.23%', '189', '963', '5', '3'], ['22 ', 'Himachal Pradesh', '6,864,602', '0.57%', '12.9%', '6,176,050', '89.97%', '688,552', '10.03%', '123', '972', '4', '3'], ['23 ', 'Tripura', '3,673,917', '0.3%', '14.8%', '2,712,464', '73.83%', '961,453', '26.17%', '350', '960', '2', '1'], ['24 ', 'Meghalaya', '2,966,889', '0.25%', '27.9%', '2,371,439', '79.93%', '595,450', '20.07%', '132', '989', '2', '1'], ['25 ', 'Manipur[c]', '2,570,390', '0.21%', '24.5%', '1,793,875', '69.79%', '776,515', '30.21%', '122', '992', '2', '1'], ['26 ', 'Nagaland', '1,978,502', '0.16%', '−0.6%', '1,407,536', '71.14%', '570,966', '28.86%', '119', '931', '1', '1'], ['27 ', 'Goa', '1,458,545', '0.12%', '8.2%', '551,731', '37.83%', '906,814', '62.17%', '394', '973', '2', '1'], ['28 ', 'Arunachal Pradesh', '1,383,727', '0.11%', '26.0%', '1,066,358', '77.06%', '317,369', '22.94%', '17', '938', '2', '1'], ['29 ', 'Puducherry', '1,247,953', '0.1%', '28.1%', '395,200', '31.67%', '852,753', '68.33%', '2,598', '1,037', '1', '1'], ['30 ', 'Mizoram', '1,097,206', '0.09%', '23.5%', '525,435', '47.89%', '571,771', '52.11%', '52', '976', '1', '1'], ['31 ', 'Chandigarh', '1,055,450', '0.09%', '17.2%', '28,991', '2.75%', '1,026,459', '97.25%', '9,252', '818', '1', '– [d]'], ['32 ', 'Sikkim', '610,577', '0.05%', '12.9%', '456,999', '74.85%', '153,578', '25.15%', '86', '890', '1', '1'], ['33 ', 'Dadra and Nagar Haveli and Daman and Diu', '585,764', '0.05%', '55.1%', '243,510', '41.57%', '342,254', '58.43%', '970', '711', '2', '– [e]'], ['34 ', 'Andaman and Nicobar Islands', '380,581', '0.03%', '6.9%', '237,093', '62.3%', '143,488', '37.7%', '46', '876', '1', '– [f]'], ['35 ', 'Ladakh', '274,000', '0.02%', '17.8%', '43,840', '16%', '230,160', '84%', '2.8', '853', '1', '– [g]'], ['36 ', 'Lakshadweep', '64,473', '0.01%', '6.3%', '14,141', '21.93%', '50,332', '78.07%', '2,013', '946', '1', '– [h]'], ['Total', 'India', '1,210,569,573', '100%', '17.7%', '833,463,448', '68.84%', '377,106,125', '31.16%', '382', '940', '543', '245 (233+12)[i]']]

#  Now we have both headers and data also Now we create pandas data frame to store our data in proper way

In [12]:
import pandas as pd

### creating data frame by headers

In [13]:
df = pd.DataFrame(columns = cleaned_headers )
df

Empty DataFrame
Columns: [Rank, State or Union Territory, Population[18][19], %India, Growth, Rural pop., %rural, Urban pop., %urban, Density[a], Sex ratio, Lok Sabha seats, Rajya Sabha seats]
Index: []

### now we will insert data in our data frame

In [14]:
for row in range(len(clean_info)):
    df.loc[row] = clean_info[row]

In [15]:
df

,Rank,State or Union Territory,Population[18][19],%India,Growth,Rural pop.,%rural,Urban pop.,%urban,Density[a],Sex ratio,Lok Sabha seats,Rajya Sabha seats
0,1,Uttar Pradesh,"199,812,341",16.51%,20.2%,"155,317,278",77.73%,"44,495,063",22.27%,828,912,80,31
1,2,Maharashtra,"112,374,333",9.28%,16%,"61,556,074",54.78%,"50,818,259",45.22%,365,929,48,19
2,3,Bihar,"104,099,452",8.6%,25.4%,"92,341,436",88.71%,"11,758,016",11.29%,1102,918,40,16
3,4,West Bengal,"91,276,115",7.54%,13.8%,"62,183,113",68.13%,"29,093,002",31.87%,1029,953,42,16
4,5,Madhya Pradesh,"72,626,809",6%,20.3%,"52,557,404",72.37%,"20,069,405",27.63%,236,931,29,11
5,6,Tamil Nadu,"72,147,030",5.96%,15.6%,"37,229,590",51.6%,"34,917,440",48.4%,555,996,39,18
6,7,Rajasthan,"68,548,437",5.66%,21.3%,"51,500,352",75.13%,"17,048,085",24.87%,201,928,25,10
7,8,Karnataka,"61,095,297",5.05%,15.6%,"37,469,335",61.33%,"23,625,962",38.67%,319,973,28,12
8,9,Gujarat,"60,439,692",4.99%,19.3%,"34,694,609",57.4%,"25,745,083",42.6%,308,919,26,11
9,10,Andhra Pradesh,"49,577,103[b]",4.1%,11.0%,"34,966,693",70.53%,"14,610,410",29.47%,303,993,25,11
10,11,Odisha,"41,974,219",3.47%,14.0%,"34,970,562",83.31%,"7,003,656",16.69%,269,979,21,10
11,12,Telangana,"35,003,674",2.89%,13.58%,"21,395,009",61.12%,"13,608,665",38.88%,312,988,17,7
12,13,Kerala,"33,406,061",2.76%,4.9%,"17,471,135",52.3%,"15,934,926",47.7%,859,"1,084",20,9
13,14,Jharkhand,"32,988,134",2.73%,22.4%,"25,055,073",75.95%,"7,933,061",24.05%,414,948,14,6
14,15,Assam,"31,205,576",2.58%,17.1%,"26,807,034",85.9%,"4,398,542",14.1%,398,958,14,7
15,16,Punjab,"27,743,338",2.29%,13.89%,"17,344,192",62.52%,"10,399,146",37.48%,551,895,13,7
16,17,Chhattisgarh,"25,545,198",2.11%,22.6%,"19,607,961",76.76%,"5,937,237",23.24%,189,991,11,5
17,18,Haryana,"25,351,462",2.09%,19.9%,"16,509,359",65.12%,"8,842,103",34.88%,573,879,10,5
18,19,NCT of Delhi,"16,787,941",1.39%,21.2%,"419,042",2.5%,"16,368,899",97.5%,"11,297",868,7,3
19,20,Jammu and Kashmir,"12,267,032",1.01%,23.6%,"9,064,220",73.89%,"3,202,812",26.11%,297,890,5,4
20,21,Uttarakhand,"10,086,292",0.83%,18.8%,"7,036,954",69.77%,"3,049,338",30.23%,189,963,5,3
21,22,Himachal Pradesh,"6,864,602",0.57%,12.9%,"6,176,050",89.97%,"688,552",10.03%,123,972,4,3
22,23,Tripura,"3,673,917",0.3%,14.8%,"2,712,464",73.83%,"961,453",26.17%,350,960,2,1
23,24,Meghalaya,"2,966,889",0.25%,27.9%,"2,371,439",79.93%,"595,450",20.07%,132,989,2,1
24,25,Manipur[c],"2,570,390",0.21%,24.5%,"1,793,875",69.79%,"776,515",30.21%,122,992,2,1
25,26,Nagaland,"1,978,502",0.16%,−0.6%,"1,407,536",71.14%,"570,966",28.86%,119,931,1,1
26,27,Goa,"1,458,545",0.12%,8.2%,"551,731",37.83%,"906,814",62.17%,394,973,2,1
27,28,Arunachal Pradesh,"1,383,727",0.11%,26.0%,"1,066,358",77.06%,"317,369",22.94%,17,938,2,1
28,29,Puducherry,"1,247,953",0.1%,28.1%,"395,200",31.67%,"852,753",68.33%,"2,598","1,037",1,1
29,30,Mizoram,"1,097,206",0.09%,23.5%,"525,435",47.89%,"571,771",52.11%,52,976,1,1
30,31,Chandigarh,"1,055,450",0.09%,17.2%,"28,991",2.75%,"1,026,459",97.25%,"9,252",818,1,– [d]
31,32,Sikkim,"610,577",0.05%,12.9%,"456,999",74.85%,"153,578",25.15%,86,890,1,1
32,33,Dadra and Nagar Haveli and Daman and Diu,"585,764",0.05%,55.1%,"243,510",41.57%,"342,254",58.43%,970,711,2,– [e]
33,34,Andaman and Nicobar Islands,"380,581",0.03%,6.9%,"237,093",62.3%,"143,488",37.7%,46,876,1,– [f]
34,35,Ladakh,"274,000",0.02%,17.8%,"43,840",16%,"230,160",84%,2.8,853,1,– [g]
35,36,Lakshadweep,"64,473",0.01%,6.3%,"14,141",21.93%,"50,332",78.07%,"2,013",946,1,– [h]
36,Total,India,"1,210,569,573",100%,17.7%,"833,463,448",68.84%,"377,106,125",31.16%,382,940,543,245 (233+12)[i]

# Here is our cleaned data and stored in pandas Data Frame

## Now we will store it in csv file

In [20]:
df.to_csv(r"S:\Scraped_and_cleaned_data.csv" , index = False)

In [17]:
# from the above command it will go in S drive's Scraped_and_cleaned_data and save it in csv format

In [19]:
df.to_json(r"S:\Scraped_and_cleaned_data.json" )